@startuml

actor "Usuário" as User

usecase "Captura de Dados Ambientais" as UC01
usecase "Processamento das Informações" as UC02
usecase "Emissão de Alertas" as UC03
usecase "Comunicação dos Dados" as UC04
usecase "Bluetooth" as UC04a
usecase "Monitor Serial" as UC04b
usecase "Alimentação do Sistema" as UC05

' Conexões principais
User --> UC01
UC02 ..> UC01 : «include»
UC03 ..> UC02 : «include»
UC04 ..> UC03 : «extend»
UC04a ..|> UC04
UC04b ..|> UC04

' Comunicação de dados dividida em Bluetooth e Monitor Serial
UC04 --> UC04a
UC04 --> UC04b

' Requisito de alimentação do sistema
UC01 --> UC05 : «require»

@enduml
